"""Compatibility facade for the ``scripts.foundry_eval`` package.

This module is the stable entry point for ``python -m scripts.evaluate_foundry``
and re-exports the public constants, dataclasses, and functions that used to
live in this single file so existing imports (including
``tests/test_evaluate_foundry.py``) keep working. The actual implementation is
split across ``scripts/foundry_eval/`` -- see that package's docstring for the
module boundaries. Add new datasets, evaluators, or suites there rather than
in this file.
"""

from scripts.foundry_eval.cli import main, parse_args
from scripts.foundry_eval.config import (
    BEHAVIOR_EVALUATOR_NAME,
    COMPREHENSIVE_AGENT_EVALUATION_NAME,
    COMPREHENSIVE_AGENT_RUN_NAME,
    COMPREHENSIVE_AGENT_SCHEDULE_ID,
    COMPREHENSIVE_DATASET_NAME,
    COMPREHENSIVE_DATASET_PATH,
    COMPREHENSIVE_DATASET_VERSION,
    COMPREHENSIVE_EVALUATION_NAME,
    COMPREHENSIVE_REPLAY_DATASET_NAME,
    COMPREHENSIVE_REPLAY_EVALUATION_NAME,
    COMPREHENSIVE_REPLAY_RUN_NAME,
    COMPREHENSIVE_RUN_NAME,
    DATASET_SHA_TAG,
    DEFAULT_CAPTURE_ATTEMPTS,
    DEFAULT_DATASET_NAME,
    DEFAULT_DATASET_PATH,
    DEFAULT_DATASET_VERSION,
    DEFAULT_EVALUATION_NAME,
    DEFAULT_METADATA_PATH,
    DEFAULT_POLL_SECONDS,
    DEFAULT_REPLAY_ROOT,
    DEFAULT_RESULTS_ROOT,
    DEFAULT_RUN_NAME,
    DEFAULT_SCHEDULE_CACHE_ROOT,
    DEFAULT_SCHEDULE_HOUR_UTC,
    DEFAULT_SCHEDULE_ID,
    PREAPPROVAL_TOOL_EVALUATOR_NAME,
    PREAPPROVAL_TOOL_EVALUATOR_VERSION,
    TOOL_CAPTURE_EVALUATOR_NAME,
    TOOL_CAPTURE_EVALUATOR_VERSION,
    TOOL_DATASET_NAME,
    TOOL_DATASET_PATH,
    TOOL_DATASET_VERSION,
    TOOL_EVALUATION_NAME,
    TOOL_OPENAPI_PATH,
    TOOL_RUN_NAME,
    UK_SOUTH_UNAVAILABLE_EVALUATORS,
    EvaluationTarget,
    InlineDataset,
    ProjectSettings,
    load_evaluation_target,
    load_project_settings,
    required_setting,
)
from scripts.foundry_eval.datasets import (
    build_comprehensive_agent_data_source_config,
    build_comprehensive_conversation_data_source_config,
    build_comprehensive_turn_data_source_config,
    build_data_source_config,
    build_tool_data_source_config,
    build_tool_score_data_source_config,
    dataset_sha256,
    load_comprehensive_dataset,
    load_dataset,
    message_text,
    prepare_dataset,
    register_dataset,
    write_jsonl,
)
from scripts.foundry_eval.evaluators import (
    PREAPPROVAL_TOOL_EVALUATOR_CODE,
    build_behavior_evaluator,
    build_comprehensive_agent_criteria,
    build_comprehensive_conversation_criteria,
    build_comprehensive_turn_criteria,
    build_preapproval_tool_evaluator,
    build_testing_criteria,
    build_tool_capture_evaluator,
    build_tool_capture_testing_criteria,
    build_tool_testing_criteria,
    ensure_behavior_evaluator,
    ensure_preapproval_tool_evaluator,
    ensure_tool_capture_evaluator,
    evaluator_criterion,
    filter_criteria_for_region,
)
from scripts.foundry_eval.replay import (
    extract_agent_output_text,
    invoke_agent_turn,
    parse_raw_agent_response,
    replay_conversations,
    replay_dataset_version,
)
from scripts.foundry_eval.runtime import (
    analyze_output_items,
    build_inline_jsonl_run_data_source,
    build_inline_literal_run_data_source,
    build_inline_run_data_source,
    build_jsonl_run_data_source,
    build_run_data_source,
    build_schedule,
    find_or_create_evaluation,
    poll_run,
    save_json,
    selected_environment,
    serialize,
    show_schedule,
    update_eval_metadata,
    uses_inline_data,
)
from scripts.foundry_eval.suites.comprehensive import (
    prepare_comprehensive_agent_evaluation,
    prepare_comprehensive_evaluations,
    run_comprehensive_evaluation,
    run_comprehensive_replay,
    upsert_comprehensive_agent_schedule,
)
from scripts.foundry_eval.suites.smoke import (
    prepare_evaluation,
    run_evaluation,
    upsert_schedule,
)
from scripts.foundry_eval.suites.tools import (
    build_intake_tool_definitions,
    build_tool_score_items,
    load_tool_dataset,
    prepare_tool_evaluation,
    run_tool_evaluation,
    score_tool_items_locally,
)

__all__ = [
    "BEHAVIOR_EVALUATOR_NAME",
    "COMPREHENSIVE_AGENT_EVALUATION_NAME",
    "COMPREHENSIVE_AGENT_RUN_NAME",
    "COMPREHENSIVE_AGENT_SCHEDULE_ID",
    "COMPREHENSIVE_DATASET_NAME",
    "COMPREHENSIVE_DATASET_PATH",
    "COMPREHENSIVE_DATASET_VERSION",
    "COMPREHENSIVE_EVALUATION_NAME",
    "COMPREHENSIVE_REPLAY_DATASET_NAME",
    "COMPREHENSIVE_REPLAY_EVALUATION_NAME",
    "COMPREHENSIVE_REPLAY_RUN_NAME",
    "COMPREHENSIVE_RUN_NAME",
    "DATASET_SHA_TAG",
    "DEFAULT_CAPTURE_ATTEMPTS",
    "DEFAULT_DATASET_NAME",
    "DEFAULT_DATASET_PATH",
    "DEFAULT_DATASET_VERSION",
    "DEFAULT_EVALUATION_NAME",
    "DEFAULT_METADATA_PATH",
    "DEFAULT_POLL_SECONDS",
    "DEFAULT_REPLAY_ROOT",
    "DEFAULT_RESULTS_ROOT",
    "DEFAULT_RUN_NAME",
    "DEFAULT_SCHEDULE_CACHE_ROOT",
    "DEFAULT_SCHEDULE_HOUR_UTC",
    "DEFAULT_SCHEDULE_ID",
    "PREAPPROVAL_TOOL_EVALUATOR_CODE",
    "PREAPPROVAL_TOOL_EVALUATOR_NAME",
    "PREAPPROVAL_TOOL_EVALUATOR_VERSION",
    "TOOL_CAPTURE_EVALUATOR_NAME",
    "TOOL_CAPTURE_EVALUATOR_VERSION",
    "TOOL_DATASET_NAME",
    "TOOL_DATASET_PATH",
    "TOOL_DATASET_VERSION",
    "TOOL_EVALUATION_NAME",
    "TOOL_OPENAPI_PATH",
    "TOOL_RUN_NAME",
    "UK_SOUTH_UNAVAILABLE_EVALUATORS",
    "EvaluationTarget",
    "InlineDataset",
    "ProjectSettings",
    "analyze_output_items",
    "build_behavior_evaluator",
    "build_comprehensive_agent_criteria",
    "build_comprehensive_agent_data_source_config",
    "build_comprehensive_conversation_criteria",
    "build_comprehensive_conversation_data_source_config",
    "build_comprehensive_turn_criteria",
    "build_comprehensive_turn_data_source_config",
    "build_data_source_config",
    "build_inline_jsonl_run_data_source",
    "build_inline_literal_run_data_source",
    "build_inline_run_data_source",
    "build_intake_tool_definitions",
    "build_jsonl_run_data_source",
    "build_preapproval_tool_evaluator",
    "build_run_data_source",
    "build_schedule",
    "build_testing_criteria",
    "build_tool_capture_evaluator",
    "build_tool_capture_testing_criteria",
    "build_tool_data_source_config",
    "build_tool_score_data_source_config",
    "build_tool_score_items",
    "build_tool_testing_criteria",
    "dataset_sha256",
    "ensure_behavior_evaluator",
    "ensure_preapproval_tool_evaluator",
    "ensure_tool_capture_evaluator",
    "evaluator_criterion",
    "extract_agent_output_text",
    "filter_criteria_for_region",
    "find_or_create_evaluation",
    "invoke_agent_turn",
    "load_comprehensive_dataset",
    "load_dataset",
    "load_evaluation_target",
    "load_project_settings",
    "load_tool_dataset",
    "main",
    "message_text",
    "parse_args",
    "parse_raw_agent_response",
    "poll_run",
    "prepare_comprehensive_agent_evaluation",
    "prepare_comprehensive_evaluations",
    "prepare_dataset",
    "prepare_evaluation",
    "prepare_tool_evaluation",
    "register_dataset",
    "replay_conversations",
    "replay_dataset_version",
    "required_setting",
    "run_comprehensive_evaluation",
    "run_comprehensive_replay",
    "run_evaluation",
    "run_tool_evaluation",
    "save_json",
    "score_tool_items_locally",
    "selected_environment",
    "serialize",
    "show_schedule",
    "update_eval_metadata",
    "upsert_comprehensive_agent_schedule",
    "upsert_schedule",
    "uses_inline_data",
    "write_jsonl",
]


if __name__ == "__main__":
    main()
